---
- hosts: localhost
  remote_user: root
  vars:
    sshd_config: {}
    ssh_config: {}
  tasks:
- name: make /tmp a tmpfs if it isnt one yet
  linefile:
    path: /mnt/etc/fstab
    regexp: '^tmpfs'
    line: 'tmpfs /tmp tmpfs rw,nosuid,mode=1777 0 0'
- file:
   path: "{{ kvm_image_root }}/{{ kvm_machine.name }}/conf.d"
   state: directory
   owner: root
   group: root
   mode: "0750"
- template:
   dest: "{{ kvm_image_root }}/{{ kvm_machine.name }}/conf.d/etc-hostname"
   src: templates/etc-hostname.j2
   owner: root
   group: root
   mode: "0644"
- template:
   dest: "{{ kvm_image_root }}/{{ kvm_machine.name }}/conf.d/root-.ssh-authorized_keys"
   src: templates/root-.ssh-authorized_keys.j2
   owner: root
   group: root
   mode: "0644"
- template:
   dest: "{{ kvm_image_root }}/{{ kvm_machine.name }}/conf.d/etc-network-interfaces"
   src: templates/etc-network-interfaces.j2
   owner: root
   group: root
   mode: "0644"
- template:
   dest: "{{ kvm_image_root }}/{{ kvm_machine.name }}/conf.d/etc-acpi-events-powerbtn"
   src: templates/etc-acpi-events-powerbtn.j2
   owner: root
   group: root
   mode: "0644"
- template:
   dest: "{{ kvm_image_root }}/{{ kvm_machine.name }}/conf.d/etc-acpi-powerbtn.sh"
   src: templates/etc-acpi-powerbtn.sh.j2
   owner: root
   group: root
   mode: "0755"
- name: resize_image
  args:
    executable: /bin/bash
  shell: |
    zfs set volsize={{ kvm_machine.image_volsize }} "{{ kvm_zfs_filesystem }}/{{ kvm_machine.name }}_disk"  || exit $?
    /usr/local/bin/fdisk_max_partition.sh /dev/zvol/{{ kvm_zfs_filesystem }}/{{ kvm_machine.name }}_disk || exit $?
    mount /dev/zvol/{{ kvm_zfs_filesystem }}/{{ kvm_machine.name }}_disk-part1 /mnt || exit $?
    btrfs filesystem resize max /mnt || exit $?
    umount /mnt
  when: "'image_volsize' in kvm_machine"
- name: mount the volume
  args:
    executable: /bin/bash
  shell: |
    partprobe /dev/zvol/{{ kvm_zfs_filesystem }}/{{ kvm_machine.name }}_disk || exit $?
    sleep 1
    mount /dev/zvol/{{ kvm_zfs_filesystem }}/{{ kvm_machine.name }}_disk-part1 /mnt || exit $?
    /usr/local/bin/copy_cfg_to_image.sh {{ kvm_image_root }}/{{ kvm_machine.name }}/conf.d /mnt || exit $?
    /usr/local/bin/replace_ssh_host_keys.sh /mnt/etc/ssh || exit $?
- name: drop root password
  linefile:
    path: /mnt/etc/shadow
    regexp: '^root:'
    line: 'root:!:17311:0:99999:7:::'
- include_tasks: prepare_debian_stretch_btrfs_mount_filesystems.yml
  with_items: "{{ kvm_machine.filesystems|default([]) }}"
  loop_control:
    loop_var: kvm_machine_filesystem
- name: umount the volume
  args:
    executable: /bin/bash
  shell: |
    umount /mnt
